Fixes 500 when user info fetched from Keycloak
When creating a users, we first attempt to fetch up to date
information from Keycloak. However, when that succeeds,
the API returns 500 because the dictionary returned contains
an extra key.

TypeError: create_user() got an unexpeTypeError: create_user() got
an unexpected keyword argument 'source'.

This fixes the above error by passing only the required keys to
create_user.